- name: Check if ECR registry secret exists
  become: yes
  become_user: ubuntu
  shell: kubectl get secret ecr-registry -n default -o name
  register: ecr_registry_secret_check
  ignore_errors: yes

- name: Create ECR registry secret if not exists
  become: yes
  become_user: ubuntu
  shell: >
    kubectl create secret docker-registry ecr-registry
    --docker-server={{URI}}
    --docker-username=AWS
    --docker-password=$(aws ecr get-login-password)
  when: ecr_registry_secret_check.rc != 0
